# Generated by Django 2.0.7 on 2018-12-07 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0015_photodislike_photolike'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uservideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.UserVideo')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uservideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.UserVideo')),
            ],
        ),
    ]
