# Generated by Django 2.0.7 on 2018-12-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_videodislike_videolike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photodislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photodislike',
            name='userphoto',
        ),
        migrations.RemoveField(
            model_name='photolike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photolike',
            name='userphoto',
        ),
        migrations.RemoveField(
            model_name='post',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='postdislike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postdislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userphoto',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userphoto',
            name='user',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PhotoDislike',
        ),
        migrations.DeleteModel(
            name='PhotoLike',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostDislike',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
