# Generated by Django 2.1.7 on 2019-04-21 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_auto_20190417_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videodislike',
            name='uservideo',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='uservideo',
        ),
        migrations.AddField(
            model_name='uservideo',
            name='users_who_disliked',
            field=models.ManyToManyField(related_name='disliked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservideo',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='VideoDislike',
        ),
        migrations.DeleteModel(
            name='VideoLike',
        ),
    ]
