# Generated by Django 2.1.7 on 2019-04-21 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20190421_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
