# Generated by Django 2.0.7 on 2018-10-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrelation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRelation',
        ),
    ]
