# Generated by Django 2.0.7 on 2018-11-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20181018_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
    ]
