# Generated by Django 2.0.7 on 2018-11-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
