# Generated by Django 2.0.5 on 2018-07-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180703_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonChat',
            new_name='Message',
        ),
    ]
