# Generated by Django 2.0.5 on 2018-07-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180703_1032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Message2All',
        ),
    ]
