# Generated by Django 2.0.5 on 2018-07-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180704_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message2all',
            old_name='user_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
