# Generated by Django 2.0.5 on 2018-07-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180704_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message2all',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
