# Generated by Django 2.0.7 on 2018-08-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.TextField(default='#000000', max_length=7),
        ),
    ]
