# Generated by Django 2.0.7 on 2018-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0002_auto_20180925_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
