# Generated by Django 2.0.7 on 2018-08-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0002_auto_20180816_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='color',
        ),
    ]
