# Generated by Django 2.0.7 on 2018-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0003_remove_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://i2.bongacams.com/00d/0e8/134/60307272da340d6aeccaf109399d57a2_thumb_big.jpg'),
        ),
    ]
