# Generated by Django 2.0.7 on 2018-09-28 12:43

import auth_custom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0006_auto_20180926_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='D:\\Coding\\Python\\Programs\\Onlyours\\media', upload_to=auth_custom.models.user_photos_path),
        ),
    ]
