# Generated by Django 2.0.7 on 2018-09-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0008_auto_20180928_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='placeholder_avatar.png', upload_to=''),
        ),
    ]
