# Generated by Django 2.1.7 on 2019-03-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0002_auto_20181005_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', '---')], default='', max_length=1),
        ),
    ]
